import type { Metadata } from "next";
import { Mooli } from "next/font/google";
import "./globals.css";
import "/css/fontStyle.css";

const fontStyle = Mooli({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Next work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontStyle.className}>{children}</body>
    </html>
  );
}
